version: '2'
services:
    ethstatsropsten:
        build: ethstats
        environment:
          - VIRTUAL_HOST=ropsten.eth.6120.eu
        env_file:
          - variables-ropsten.env
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
    relayropsten:
        build: relay
        volumes:
          - /data/relayropsten:/data
        env_file:
          - variables-ropsten.env
        ports:
          - 0.0.0.0:30303:30303
          - 0.0.0.0:8557:8546
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
    ethstatsrinkeby:
        build: ethstats
        environment:
          - VIRTUAL_HOST=rinkeby.eth.6120.eu
        env_file:
          - variables-rinkeby.env
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
    relayrinkeby:
        build: relay
        environment:
          - ETHSTATS=ethstatsrinkeby
        volumes:
          - /data/relayrinkeby:/data
        env_file:
          - variables-rinkeby.env
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
    ethstatsgoerli:
        build: ethstats
        environment:
          - VIRTUAL_HOST=goerli.eth.6120.eu
        env_file:
          - variables-goerli.env
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
    relaygoerli:
        build: relay
        environment:
          - ETHSTATS=ethstatsgoerli
        volumes:
          - /data/relaygoerli:/data
        env_file:
          - variables-goerli.env
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
